In [ ]:
# Import library

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
# Load dataset

df = pd.read_csv('data/tempat_wisata_yogyakarta.csv')
df.head()

,no,nama,vote_average,vote_count,type,htm_weekday,htm_weekend,latitude,longitude,description
0,9,Candi Borobudur,4.7,81922,Budaya dan Sejarah,50000.0,50000.0,-7.607087,110.203623,Candi yang pernah masuk sebagai salah satu dar...
1,10,Candi Prambanan,4.7,71751,Budaya dan Sejarah,50000.0,50000.0,-7.751835,110.491532,Candi Prambanan adalah kompleks candi Hindu te...
2,24,Tebing Breksi,4.4,51431,Alam,10000.0,10000.0,-7.781477,110.504576,Tebing Breksi merupakan tempat wisata yang ber...
3,343,Gembira Loka Zoo,4.5,36337,Buatan,20000.0,25000.0,-7.806234,110.396798,Gambira Loka adalah kebun binatang yang berada...
4,346,The Palace of Yogyakarta (Keraton Yogyakarta),4.6,30091,Budaya dan Sejarah,8000.0,8000.0,-7.805284,110.364203,Kompleks keraton merupakan museum yang menyimp...

In [ ]:
# Membuat kolom label

df['recommended'] = ((df['vote_average'] >= 4.5) & (df['vote_count'] >= 10000)).astype(int)
df[['vote_average', 'vote_count', 'recommended']].head()

   vote_average  vote_count  recommended
0           4.7       81922            1
1           4.7       71751            1
2           4.4       51431            0
3           4.5       36337            1
4           4.6       30091            1

In [ ]:
# Pilih fitur dan target

features = ['vote_average', 'vote_count', 'htm_weekday', 'htm_weekend']
X = df[features].fillna(0)  # isi NaN dengan 0
y = df['recommended']

In [7]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [9]:
print('Akurasi:', accuracy_score(y_test, y_pred))
print('\nLaporan Klasifikasi:\n', classification_report(y_test, y_pred, target_names=['Tidak Rekomendasi', 'Rekomendasi']))

Akurasi: 0.972027972027972

Laporan Klasifikasi:
                    precision    recall  f1-score   support

Tidak Rekomendasi       0.98      0.99      0.99       136
      Rekomendasi       0.80      0.57      0.67         7

         accuracy                           0.97       143
        macro avg       0.89      0.78      0.83       143
     weighted avg       0.97      0.97      0.97       143

In [10]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X, y)

# Training ulang
model = GaussianNB()
model.fit(X_resampled, y_resampled)
y_pred = model.predict(X_test)

print('Akurasi:', accuracy_score(y_test, y_pred))
print('\nLaporan Klasifikasi:\n', classification_report(y_test, y_pred, target_names=['Tidak Rekomendasi', 'Rekomendasi']))

Akurasi: 0.951048951048951

Laporan Klasifikasi:
                    precision    recall  f1-score   support

Tidak Rekomendasi       1.00      0.95      0.97       136
      Rekomendasi       0.50      1.00      0.67         7

         accuracy                           0.95       143
        macro avg       0.75      0.97      0.82       143
     weighted avg       0.98      0.95      0.96       143