# import library

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("data/klasifikasimhs.csv")

df.head()

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
0,0,PNS,10000000,3,1,0
1,0,TNI/POLRI,8000000,2,2,1
2,1,Petani,4000000,4,0,0
3,1,Nelayan,3000000,5,1,0
4,0,Buruh,2000000,2,1,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tempat Tinggal               100 non-null    int64
 1   Pekerjaan Orang Tua          100 non-null    object
 2   Penghasilan Orang Tua        100 non-null    int64
 3   Jumlah Tanggungan Orang Tua  100 non-null    int64
 4   Kendaraan                    100 non-null    int64
 5   Kelayakan Keringanan UKT     100 non-null    object
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [7]:
df.isnull().sum()

Tempat Tinggal                 0
Pekerjaan Orang Tua            0
Penghasilan Orang Tua          0
Jumlah Tanggungan Orang Tua    0
Kendaraan                      0
Kelayakan Keringanan UKT       0
dtype: int64

In [8]:
df.describe()

,Tempat Tinggal,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan
count,100.000000,1.000000e+02,100.000000,100.000000
mean,0.500000,5.427000e+06,2.590000,1.070000
std,0.502519,2.533128e+06,1.129002,0.655282
min,0.000000,7.000000e+05,1.000000,0.000000
25%,0.000000,3.000000e+06,2.000000,1.000000
50%,0.500000,5.500000e+06,2.000000,1.000000
75%,1.000000,8.000000e+06,3.250000,1.250000
max,1.000000,1.000000e+07,5.000000,2.000000